service_name: "article_hub"
configuration_parameters:
  - port: 5555
  - host: 0.0.0.0
  - debug: false
  - scrap_service_route: "/scrapping"
  - urls_data_scraping: "http://bibdigital.sid.inpe.br"
  - queimadas_authors: ["Alberto Waingort Setzer", "Renata Libonati", "Fabiano Morelli", "Fillipe Pereira Bueno de Almeida", "Caíque Frederico Pereira de Moura", "Fabrício Galende Marques de Carvalho", "Elisa Beninca Martins", "Ryan Alves de Quadros"]
  - system_prompt: ""
  - llm_model_path: "/app/models/qwen2.5-1.5b-instruct-q4_k_m.gguf"
  - llm_model_repo: "Qwen/Qwen2.5-1.5B-Instruct-GGUF"
  - llm_model_file: "qwen2.5-1.5b-instruct-q4_k_m.gguf"